name: Update League One Standings

on:
  workflow_dispatch:
  schedule:
    - cron: '45 19 * * 1-5'
    - cron: '*/15 20-23 * * 1-5'
    - cron: '*/15 12-23 * * 6,0'
    - cron: '0 0 * * *'

permissions:
  contents: write 

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get current season year
        id: season
        run: |
          MONTH=$(date -u +"%m")
          YEAR=$(date -u +"%Y")
          if [ "$MONTH" -lt 6 ]; then
            echo "SEASON=$((YEAR - 1))" >> $GITHUB_ENV
          else
            echo "SEASON=$YEAR" >> $GITHUB_ENV
          fi

      - name: Fetch League One Standings
        run: |
          echo "Fetching standings for season $SEASON"
          curl -s --request GET \
            --url "https://api-football-v1.p.rapidapi.com/v3/standings?season=$SEASON&league=41" \
            --header "X-RapidAPI-Key: ${{ secrets.RAPIDAPI_KEY }}" \
            --header "X-RapidAPI-Host: api-football-v1.p.rapidapi.com" \
            | jq . > data/standings.json

      - name: Commit and Push if Updated
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add data/standings.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update standings"
            git push
          fi
