name: Update Cardiff Standings

on:
  workflow_dispatch:
  schedule:
    #- cron: '45 19 * * 1-5'
    #- cron: '*/15 20-23 * * 1-5'
    #- cron: '*/15 12-23 * * 6,0'
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Detect Cardiff’s League and Season
        run: |
          TEAM_ID=43
          MONTH=$(date +%m)
          YEAR=$(date +%Y)

          if [ "$MONTH" -lt 8 ]; then
            SEASON=$((YEAR - 1))
          else
            SEASON=$YEAR
          fi

          echo "📅 Using season: $SEASON"
          mkdir -p tmp

          response=$(curl -s --request GET \
            --url "https://api-football-v1.p.rapidapi.com/v3/standings?season=${SEASON}&team=${TEAM_ID}" \
            --header "X-RapidAPI-Key: $RAPIDAPI_KEY" \
            --header "X-RapidAPI-Host: api-football-v1.p.rapidapi.com")

          echo "$response" | jq . > tmp/cardiff-response.json

          LEAGUE_ID=$(echo "$response" | jq -r '.response[0].league.id')
          LEAGUE_NAME=$(echo "$response" | jq -r '.response[0].league.name')

          if [ "$LEAGUE_ID" = "null" ] || [ -z "$LEAGUE_ID" ]; then
            echo "❌ Could not determine league ID. Exiting."
            cat tmp/cardiff-response.json
            exit 1
          fi

          echo "✅ Cardiff are in $LEAGUE_NAME (League ID $LEAGUE_ID) for $SEASON"
          echo "LEAGUE_ID=$LEAGUE_ID" >> $GITHUB_ENV
          echo "SEASON=$SEASON" >> $GITHUB_ENV

      - name: Fetch and Flag Cardiff in League Standings with Last Season Info
        run: |
          echo "📥 Fetching current season standings..."
          CURRENT=$(curl -s --request GET \
            --url "https://api-football-v1.p.rapidapi.com/v3/standings?season=${SEASON}&league=${LEAGUE_ID}" \
            --header "X-RapidAPI-Key: $RAPIDAPI_KEY" \
            --header "X-RapidAPI-Host: api-football-v1.p.rapidapi.com")

          echo "$CURRENT" | jq . > tmp/current-standings.json

          echo "📅 Determining last season (${SEASON} - 1)..."
          LAST_SEASON=$((SEASON - 1))

          echo "🧠 Building last season info for all teams..."
          jq -r '.response[0].league.standings[0][] | .team.id' tmp/current-standings.json > tmp/team-ids.txt

          echo '{ }' > tmp/last-season-map.json

          while read -r TEAM_ID; do
            echo "🔎 Checking team $TEAM_ID"
            TEAM_DATA=$(curl -s --request GET \
              --url "https://api-football-v1.p.rapidapi.com/v3/standings?season=${LAST_SEASON}&team=${TEAM_ID}" \
              --header "X-RapidAPI-Key: $RAPIDAPI_KEY" \
              --header "X-RapidAPI-Host: api-football-v1.p.rapidapi.com")

            LAST_LEAGUE=$(echo "$TEAM_DATA" | jq -r '.response[0].league.name // "Unknown"')
            LAST_POSITION=$(echo "$TEAM_DATA" | jq -r '.response[0].league.standings[0][0].rank // "?"')

            jq --arg id "$TEAM_ID" \
               --arg league "$LAST_LEAGUE" \
               --arg pos "$LAST_POSITION" \
               '. + {($id): {lastSeasonLeague: $league, lastSeasonPosition: $pos}}' \
               tmp/last-season-map.json > tmp/tmp-map.json && mv tmp/tmp-map.json tmp/last-season-map.json
          done < tmp/team-ids.txt

          echo "🛠️ Merging last season data into current standings..."
          jq --slurpfile map tmp/last-season-map.json '
            .response[0].league.standings[0] |= map(
              . + {
                highlight: (if .team.id == 43 then true else false end),
                lastSeasonLeague: ($map[0][(.team.id|tostring)]?.lastSeasonLeague // "Unknown"),
                lastSeasonPosition: ($map[0][(.team.id|tostring)]?.lastSeasonPosition // "?")
              }
            )
          ' tmp/current-standings.json > data/standings.json

          echo "✅ Merged standings.json saved."

      - name: Clean old logos
        run: |
          echo "🧹 Cleaning old logos"
          rm -rf assets/logos

      - name: Download team icons
        run: |
          mkdir -p assets/logos
          jq -r '.response[0].league.standings[0][] | "\(.team.id) \(.team.logo)"' data/standings.json |
          while read -r id url; do
            echo "🖼️  Downloading logo for team $id"
            curl -s -o "assets/logos/${id}.png" "$url"
          done

      - name: Download league icon
        run: |
          curl -s -o league-icon.png "https://media.api-sports.io/football/leagues/${LEAGUE_ID}.png"

      - name: Add and commit league icon
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add league-icon.png
          if git diff --cached --quiet; then
            echo "No changes in league icon."
          else
            git commit -m "Update league icon for league ${LEAGUE_ID}"
            git push
          fi

      - name: Commit and Push if Changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add data/standings.json tmp/cardiff-response.json assets/logos/
          if git diff --cached --quiet; then
            echo "🟢 No changes to commit."
          else
            git commit -m "Update standings and team icons"
            git push
          fi
