name: Update Cardiff Standings

on:
  workflow_dispatch:
  schedule:
    # Refresh every 15 minutes from 7:45 PM to 11:59 PM UTC Monday-Friday
    - cron: '45 19 * * 1-5'
    - cron: '*/15 20-23 * * 1-5'
    # Refresh every 15 minutes from 12:00 PM to 11:59 PM UTC Saturday-Sunday
    - cron: '*/15 12-23 * * 6,0'
    # Single refresh at midnight UTC every day (just in case)
    - cron: '0 0 * * *'

permissions:
  contents: write
  
jobs:
  update:
    runs-on: ubuntu-latest
    env:
      SEASON: ${{ github.event.inputs.season || '2024' }}  # fallback, optional input to override season
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch Standings for Cardiff City (team 43)
        run: |
          curl -s --request GET \
            --url "https://api-football-v1.p.rapidapi.com/v3/standings?season=$SEASON&team=43" \
            --header "X-RapidAPI-Key: ${{ secrets.RAPIDAPI_KEY }}" \
            --header "X-RapidAPI-Host: api-football-v1.p.rapidapi.com" \
            > data/standings.json

      - name: Commit and Push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add data/standings.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update Cardiff City standings for season $SEASON"
            git push
          fi
