name: Update Cardiff Standings

on:
  workflow_dispatch:
  schedule:
 #   - cron: '45 19 * * 1-5'
 #   - cron: '*/15 20-23 * * 1-5'
 #   - cron: '*/15 12-23 * * 6,0'
 #   - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Detect Cardiff’s League and Season
        run: |
          TEAM_ID=43
          MONTH=$(date +%m)
          YEAR=$(date +%Y)

          if [ "$MONTH" -lt 8 ]; then
            SEASON=$((YEAR - 1))
          else
            SEASON=$YEAR
          fi

          echo "📅 Using season: $SEASON"
          mkdir -p tmp

          response=$(curl -s --request GET \
            --url "https://api-football-v1.p.rapidapi.com/v3/standings?season=${SEASON}&team=${TEAM_ID}" \
            --header "X-RapidAPI-Key: ${{ secrets.RAPIDAPI_KEY }}" \
            --header "X-RapidAPI-Host: api-football-v1.p.rapidapi.com")

          echo "$response" | jq . > tmp/cardiff-response.json

          LEAGUE_ID=$(echo "$response" | jq -r '.response[0].league.id')
          LEAGUE_NAME=$(echo "$response" | jq -r '.response[0].league.name')

          if [ "$LEAGUE_ID" = "null" ] || [ -z "$LEAGUE_ID" ]; then
            echo "❌ Could not determine league ID. Exiting."
            cat tmp/cardiff-response.json
            exit 1
          fi

          echo "✅ Cardiff are in $LEAGUE_NAME (League ID $LEAGUE_ID) for $SEASON"
          echo "LEAGUE_ID=$LEAGUE_ID" >> $GITHUB_ENV
          echo "SEASON=$SEASON" >> $GITHUB_ENV

      - name: Fetch and Flag Cardiff in League Standings with Dynamic Last Season Info
        run: |
          echo "📥 Fetching current season standings..."
          CURRENT=$(curl -s --request GET \
            --url "https://api-football-v1.p.rapidapi.com/v3/standings?season=${SEASON}&league=${LEAGUE_ID}" \
            --header "X-RapidAPI-Key: ${{ secrets.RAPIDAPI_KEY }}" \
            --header "X-RapidAPI-Host: api-football-v1.p.rapidapi.com")

          echo "$CURRENT" | jq . > tmp/current-standings.json

          echo "📅 Determining last season (${SEASON} - 1)..."
          LAST_SEASON=$((SEASON - 1))

          echo "📋 Getting all leagues from last season..."
          ALL_LEAGUES=$(curl -s --request GET \
            --url "https://api-football-v1.p.rapidapi.com/v3/leagues?season=${LAST_SEASON}" \
            --header "X-RapidAPI-Key: ${{ secrets.RAPIDAPI_KEY }}" \
            --header "X-RapidAPI-Host: api-football-v1.p.rapidapi.com")

          echo "$ALL_LEAGUES" | jq . > tmp/leagues-${LAST_SEASON}.json

          echo "📌 Extracting relevant league IDs..."
          echo "$ALL_LEAGUES" | jq -r '.response[] | select(.league.type == "League") | .league.id' > tmp/league-ids.txt

          echo "🧠 Building last season map of team -> {league, position} ..."
          mkdir -p tmp/last-season
          echo '{}' > tmp/last-season-map.json

          while read -r LEAGUE_ID_LAST; do
            echo "🌀 Checking league $LEAGUE_ID_LAST..."
            STANDING=$(curl -s --request GET \
              --url "https://api-football-v1.p.rapidapi.com/v3/standings?season=${LAST_SEASON}&league=${LEAGUE_ID_LAST}" \
              --header "X-RapidAPI-Key: ${{ secrets.RAPIDAPI_KEY }}" \
              --header "X-RapidAPI-Host: api-football-v1.p.rapidapi.com")

            echo "$STANDING" > tmp/last-season/league-${LEAGUE_ID_LAST}.json

            jq -c --arg leagueId "$LEAGUE_ID_LAST" '
              .response[0].league as $league |
              (if (.standings and .standings[0]) then
                 .standings[0][]
               else
                 empty
               end) |
              { "\(.team.id)": {
                  lastSeasonLeague: $league.name,
                  lastSeasonPosition: .rank
                }
              }
            ' <<< "$STANDING" >> tmp/last-season-map-lines.json
          done < tmp/league-ids.txt

          echo "📦 Combining last season data..."
          jq -s 'reduce .[] as $item ({}; . * $item)' tmp/last-season-map-lines.json > tmp/last-season-map.json

          echo "🛠️  Merging last season data into current standings..."
          jq --slurpfile map tmp/last-season-map.json '
            .response[0].league.standings[0] |= map(
               . + {
                highlight: (if .team.id == 43 then true else false end),
                lastSeasonLeague: ($map[0][(.team.id|tostring)]?.lastSeasonLeague // "Unknown"),
                lastSeasonPosition: ($map[0][(.team.id|tostring)]?.lastSeasonPosition // "?")
              }
            )
          ' tmp/current-standings.json > data/standings.json

          echo "✅ Merged standings.json saved."

      - name: Clean old logos
        run: |
          echo "🧹 Cleaning old logos"
          rm -rf assets/logos

      - name: Download team icons
        run: |
          mkdir -p assets/logos
          jq -r '.response[0].league.standings[0][] | "\(.team.id) \(.team.logo)"' data/standings.json |
          while read -r id url; do
            echo "🖼️  Downloading logo for team $id"
            curl -s -o "assets/logos/${id}.png" "$url"
          done

      - name: Download league icon
        run: |
          curl -s -o league-icon.png "https://media.api-sports.io/football/leagues/${LEAGUE_ID}.png"

      - name: Add and commit league icon
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add league-icon.png
          if git diff --cached --quiet; then
            echo "No changes in league icon."
          else
            git commit -m "Update league icon for league ${LEAGUE_ID}"
            git push
          fi

      - name: Commit and Push if Changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add data/standings.json tmp/cardiff-response.json assets/logos/
          if git diff --cached --quiet; then
            echo "🟢 No changes to commit."
          else
            git commit -m "Update standings and team icons"
            git push
          fi
