name: Update League One Standings

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:     # Optional manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch League One Standings
        run: |
          curl -s --request GET \
            --url 'https://api-football-v1.p.rapidapi.com/v3/standings?season=2024&league=41' \
            --header 'X-RapidAPI-Key: ${{ secrets.RAPIDAPI_KEY }}' \
            --header 'X-RapidAPI-Host: api-football-v1.p.rapidapi.com' \
            | jq . > data/standings.json

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add data/standings.json
          git commit -m "Update standings"
          git push
