name: Update League One Standings

on:
  schedule:
    # Refresh every 15 minutes from 7:45 PM to 11:59 PM UTC Monday-Friday
    - cron: '45 19 * * 1-5'
    - cron: '*/15 20-23 * * 1-5'
    # Refresh every 15 minutes from 12:00 PM to 11:59 PM UTC Saturday-Sunday
    - cron: '*/15 12-23 * * 6,0'
    # Plus a single refresh at midnight UTC every day (just in case)
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch League One Standings
        run: |
          curl -s --request GET \
            --url 'https://api-football-v1.p.rapidapi.com/v3/standings?season=2024&league=41' \
            --header 'X-RapidAPI-Key: ${{ secrets.RAPIDAPI_KEY }}' \
            --header 'X-RapidAPI-Host: api-football-v1.p.rapidapi.com' \
            | jq . > data/standings.json

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add data/standings.json
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update standings"
            git push
          fi
